### ISSUE TITLE
Final_Project of Arielle Herman

### ISSUE THREAD

**Issue by aeherman** [QMSS-G5072-2020/Final_Project_Herman_Arielle#1]
3779164

Edit: sorry, that was the wrong commit.  Here is the right one:  618b22c
@SUN-Wenjun @tbrambor @lonadai0121

**Comment by lonadai0121** [comment]
3.5/5 Satisfactory Project: lack of complexity. The chosen task was acceptable, but fairly conservative in ambition.
3/3 well commented and documented
3/3 The code is efficient, correct, and minimal
3/3 The package structure is clear, easy to follow, and closely matches the structure discussed in class.
3/3 The package, data, and functions’ documentation is clear and easy to follow. 
3/3 The package installs without problems.
3/3 The package contains automated testing of at least some of the main functions and these tests run without errors.
